# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

## paginate: 10 # pagination based on number of posts
paginate_path: "page/:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: alexrochas
google_analytics: UA-83264734-1
title: "[alex_rocha]"

include:
  - _pages
  - _posts

exclude:
  - vendor/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - README.md
  - LICENSE

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
      start_line: 1
    span:
      line_numbers: false

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: "[alex_rocha]"

description:
author:
  name: "[alex_rocha] by alex"
  email: alexsuzume@gmail.com
  github: alexrochas
  twitter: alexsuzume
  pinterest: alexrochas
  linkedin: alexrochas
  medium: alexrocha_15255
  bio: 🇧🇷Senior Software Developer
  email_md5: e6f244d374347e94e7f33897d8f3e417

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

svg:
  optimize: true

twitter:
  username: alexsuzume

url: "http://alexrocha.de"

webmaster_verifications:
  google: OzMjWKKnJc_zMK4N0NCn7tAa9ZIuiEzXdgAPZdaqIEI

plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-seo-tag # https://maxchadwick.xyz/blog/twitter-cards-for-jekyll-with-jekyll-seo-tag

plugins:

pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  trail:
    before: 2
    after: 2
  limit: 0
  sort_field: 'date'
  sort_reverse: true