name: Jekyll site CI

on:
  push:
    branches:
      - master # Set this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'  # Specify the Ruby version you need

    - name: Configure Bundler
      run: |
        gem install bundler
        bundle config set path 'vendor/bundle'  # Configure Bundler to use local path for gems

    - name: Install dependencies
      run: |
        bundle install  # Install dependencies locally

    - name: Build and test
      run: |
        bundle exec jekyll build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
